<?php
function getProfileThumb(){
    if ($user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id())) {
        if (!$user->user_picture->isEmpty()) {
          $picture = $user->user_picture->view('small');
        }
        else {
          $picture = 0;
        }
      }
    return $picture;
}

function seminarian_preprocess(&$variables, $hook){
    $variables["profile_picture"] = getProfileThumb();
}
