<?php
function getProfileImage(){
    if ($user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id())) {
        if (!$user->user_picture->isEmpty()) {
          $picture = $user->user_picture->view('large');
        }
        else {
          $picture = '<i class="fas fa-user"></i>';
        }
      }
    return $picture;
}

function seminarian_preprocess(&$variables, $hook){
    $variables["profile_picture"] = getProfileImage();
}
